# Generated by Django 3.1.6 on 2021-02-13 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AIS_ERP', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AIS_ERP',
            new_name='AisErp',
        ),
    ]
